context("LagrangeMgmtDesign")

test_that("initializes with context, divisions, and valid parameters", {
  TEST_DIRECTORY <- test_path("test_inputs")
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = 10,
    establish_pr = NULL,
    f_obj = NULL,
    f_deriv = NULL,
    f_pos = NULL,
    alpha_unconstr = NULL,
    alpha_min = NULL,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    paste("Divisions parameter must be a 'bsdesign::Divisions' or inherited",
          "class object."))
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:5,
    f_obj = NULL,
    f_deriv = NULL,
    f_pos = NULL,
    alpha_unconstr = NULL,
    alpha_min = NULL,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    paste("The establishment probability must be numeric,  >= 0, and match",
          "the number of division parts."))
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = NULL,
    f_deriv = NULL,
    f_pos = NULL,
    alpha_unconstr = NULL,
    alpha_min = NULL,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    "The unconstrained marginal benefit alpha value must be numeric.")
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = NULL,
    f_deriv = NULL,
    f_pos = NULL,
    alpha_unconstr = 0,
    alpha_min = NULL,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    "The minimum marginal benefit alpha value must be numeric.")
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = NULL,
    f_deriv = NULL,
    f_pos = NULL,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    "The objective function should have form function(x_alloc).",
    fixed = TRUE)
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function() 0,
    f_pos = NULL,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    "The derivative function should have form function(x_alloc).",
    fixed = TRUE)
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a, b) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    paste("The pseudo-inverse-derivative function should have form",
          "function(alpha)."), fixed = TRUE)
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = NULL,
    f_inv_unit_eff = NULL),
    "The unit effectiveness function should have form function(x_alloc).",
    fixed = TRUE)
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = NULL),
    paste("The inverse unit effectiveness function should have form",
          "function(unit_effectiveness)."), fixed = TRUE)
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = function(s) 0,
    budget = 0),
    "The budget parameter must be numeric and > 0.")
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = function(s) 0,
    overall_pr = 2),
    paste("The overall probability/effectiveness parameter must be numeric,",
          ">= 0 and <= 1."))
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = function(s) 0,
    min_alloc = 1:5),
    paste("The minimum allocation parameter must be a numeric vector with",
          "values for each division part."))
  expect_error(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = function(s) 0,
    search_alpha = 0),
    "The search alpha indicator parameter must be logical.")
  expect_silent(mgmt_design <- LagrangeMgmtDesign(
    context = ManageContext("test"),
    divisions = bsdesign::Divisions(matrix(1:10)),
    establish_pr = 1:10,
    f_obj = function(x) 0,
    f_deriv = function(x) 0,
    f_pos = function(a) 0,
    alpha_unconstr = 0,
    alpha_min = -1,
    f_unit_eff = function(x) 0,
    f_inv_unit_eff = function(s) 0))
  expect_is(mgmt_design, "LagrangeMgmtDesign")
  expect_equal(mgmt_design$get_cost_allocation(), 0)
})
